services:
  hue:
    # image: gethue/hue:latest
    build: ./hue-build
    ports:
      - "8888:8888"  # Map container port 8888 to host port 8888
    # environment:
    #   # Add any additional environment variables needed by Hue here
    volumes:
      # Add any volume mounts needed for persistence here
      # - ./hue-build/mnt/config/hue.ini:/usr/share/hue/desktop/conf/hue.ini
      - ./hue-build/mnt/config/hue.ini:/usr/share/hue/desktop/conf/hue.ini
  postgres:
    image: postgres:16.2
    ports: 
      - 0.0.0.0:5432:5432
    environment:
      POSTGRES_USER: meowuser  # Username for PostgreSQL
      POSTGRES_PASSWORD: meowmeow  # Password for PostgreSQL (change this!)
    volumes:
      - postgres_data2:/var/lib/postgresql/data  # Persistent storage for database

  # pgadmindesktop:
  #   image: dpage/pgadmin4:8.5
  #   ports:
  #     # - "80:5050"  # Map pgAdmin port to host port 5050
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@meow.com  # Default pgAdmin email
  #     PGADMIN_DEFAULT_PASSWORD: admin  # Default pgAdmin password (change this!)
  #   depends_on:
  #     - postgres  # Start pgAdmin after PostgreSQL
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de


  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure



volumes:
  postgres_data2: {}  # Define an empty volume for persistent storage
  datanode: {}
  namenode: {}